version: '2'
services:
  # mysql:
  #   image: mysql:5.7
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  #   ports:
  #     - ${MYSQL_PORT}:3306
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${POSTGRES_DEFAULT_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DEFAULT_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DEFAULT_DB}
    ports:
      - ${POSTGRES_PORT}:5432
 
  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - ${MONGO_PORT}:27017
 
  # elasticsearch2:
  #   image: elasticsearch:2-alpine
  #   ports:
  #     - ${ELASTICSEARCH2_REST_PORT}:9200
  #     - ${ELASTICSEARCH2_NODE_PORT}:9300
 
  # elasticsearch5:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
  #   ports:
  #     - ${ELASTICSEARCH5_REST_PORT}:9201
  #     - ${ELASTICSEARCH5_NODE_PORT}:9301
  #   environment:
  #     - discovery.type=single-node
  #     - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
 
  redis:
    image: redis:alpine
    ports:
      - ${REDIS_PORT}:6379
 
  # beanstalkd:
  #   image: schickling/beanstalkd
  #   ports:
  #     - ${BEANSTALKD_PORT}:11300
 
  # memcached:
  #   image: memcached:alpine
  #   ports:
  #     - ${MEMCACHED_PORT}:11211
  
  # cassandra:
  #   image: cassandra:latest
  #   ports:
  #     - ${CASSANDRA_PORT}:9042
  # flink-jobmanager:
  #   image: flink:1.6.4
  #   expose:
  #     - "6123"
  #   ports:
  #     - "8081:8081"
  #   command: jobmanager
  #   links:
  #     - zookeeper
  #     - kafka
  #   environment:
  #     - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
  #   env_file:
  #     - ./sievex-invoker.env
  # flink-taskmanager:
  #   image: flink:1.6.4
  #   expose:
  #     - "6121"
  #     - "6122"
  #   depends_on:
  #     - flink-jobmanager
  #   command: taskmanager
  #   links:
  #     - "flink-jobmanager:flink-jobmanager"
  #     - cassandra
  #     - kafka
  #     - zookeeper
  #   environment:
  #     - JOB_MANAGER_RPC_ADDRESS=flink-jobmanager
  #   env_file:
  #     - ./sievex-invoker.env
  # kafdrop:
  #   image: obsidiandynamics/kafdrop:latest
  #   container_name: kafdrop
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_BROKERCONNECT: kafka:39092
  #     JVM_OPTS: "-Xms32M -Xmx64M"
  #     SERVER_SERVLET_CONTEXTPATH: "/"
  # zookeeper:
  #   image: wurstmeister/zookeeper
  #   ports:
  #     - 2181:2181
  # kafka:
  #   image: wurstmeister/kafka:2.11-0.11.0.2
  #   ports:
  #     - 9092:9092
  #   environment:
  #     KAFKA_BROKER_ID: 1001
  #     KAFKA_RESERVED_BROKER_MAX_ID: 100000
  #     # - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
  #     KAFKA_LISTENERS: PLAINTEXT://:9092
  #     KAFKA_ADVERTISED_HOST_NAME: kafka
  #     KAFKA_ADVERTISED_PORT: 9092
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_HEAP_OPTS: -Xms128m -Xmx512m
  #   depends_on:
  #     - zookeeper
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

  # rabbitmq:
  #   image: rabbitmq:3-management-alpine
  #   container_name: 'rabbitmq-local'
  #   ports:
  #     - 5672:5672
  #     - 15672:15672
  #   volumes:
  #     - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
  #     - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq